server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: false
  thymeleaf:
    cache: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
app:
  activation:
    base-url: ${ACTIVATION_BASE_URL}
  reset-password:
    base-url: ${RESET_PASSWORD_BASE_URL}
logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.springframework.web: INFO
payos:
  clientId: ${PAYOS_CLIENT_ID}
  apiKey: ${PAYOS_API_KEY}
  webhookSecret: ${PAYOS_WEBHOOK_SECRET}
  base-url: ${PAYOS_BASE_URL:https://api-merchant.payos.vn}
  return-url: ${PAYOS_RETURN_URL}
  cancel-url: ${PAYOS_CANCEL_URL}

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD}
  api_key: ${CLOUDINARY_KEY}
  api_secret: ${CLOUDINARY_SECRET}

