name: CI/CD EEWMS (Windows + OIDC)

on:
  push:
    branches: [ "master", "prod" ]
  pull_request:
    branches: [ "master", "prod" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-build
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21 (Microsoft Build of OpenJDK)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
          cache: 'maven'

      - name: Maven Test
        run: mvn -B -ntp -f Backend/eewms/pom.xml test

      - name: Package
        run: mvn -B -ntp -f Backend/eewms/pom.xml -DskipTests package

      - name: Upload artifact (push only)
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: eewms-jar
          path: Backend/eewms/target/*.jar

  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/prod'
    runs-on: windows-latest
    environment:
      name: Production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
    concurrency:
      group: ${{ github.workflow }}-deploy
      cancel-in-progress: true
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: eewms-jar
          path: build

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: build\*.jar
        env:
          SPRING_PROFILES_ACTIVE: prod
