name: CI/CD EEWMS (Linux + OIDC)

on:
  push:
    branches: [ "prod" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-build
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21 (Microsoft Build of OpenJDK)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
          cache: 'maven'

      - name: Build with Maven (skip tests)
        run: mvn -f Backend/eewms/pom.xml -B -ntp -DskipTests clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: eewms-jar
          path: Backend/eewms/target/*.jar

  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    concurrency:
      group: ${{ github.workflow }}-deploy
      cancel-in-progress: true
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: eewms-jar
          path: build

      - name: List downloaded files (debug)
        run: ls -lah build

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Thiết lập App Settings trực tiếp trên Web App (QUAN TRỌNG)
      - name: Configure App Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          app-settings-json: >
            [
              {"name": "SPRING_PROFILES_ACTIVE", "value": "prod", "slotSetting": false}
            ]

      - name: Deploy to Azure Web App (Linux Java SE 21)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: build/*.jar
